---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qui
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qui.efym.net`)
      kind: Rule
      middlewares:
        - name: authelia
          namespace: authelia
      services:
        - name: qui
          port: 7476
  tls:
    secretName: efym-net-tls
