---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qui-downloads
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/downloads
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
