apiVersion: v1
kind: Secret
metadata:
    name: qui
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:7UOTQrwBOVreyC0dHU+IIZA8oTr3Wih5UCTv2GTZU4/HIdGyteP99Dr8ymWr8JrfEMbKzz4MgxBCoduIqplf+uPao9E+Lssz6JcN5WA3WxZ0PS4fi5sPSorIc5fNft6u/xkvrsAHCaQeHeekewffzmTdFC3jq+aEiuaU9VHM8FFSkPiFJY2UBxkQXWyOHKXcLPDrk+H9fvTlUBSg5rYjtA0f4mWaPY9HIHpAmDb2381bfS+bh5V0V2CzkIm4Vhh7EKpBEjoQx8vXwumMrYOMw6AlVmEKR9yRSrzoO/cLUar4kiAq9AOxlG4mI9O2NsCq7ia7Y6NQNjgIal4+sMuP/gbxGqiKDE/1D7QjqtC/n/RfpCUuljTUt0Rx4kAFBv9LWvvt,iv:0VzIzTbqA0UkR3ogquFwKoNJY/leEhomXps1+sfwLx0=,tag:ixD9vMPY6ssPSxHFrj+fEg==,type:str]
sops:
    age:
        - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVDM0b2Y2M0tsUUc1d0Rj
            WTYyVUkyY3c4czlnSzdTOCtQOEtYbENkUkI0CjgxZHkxRjBXb0xhNmtpeS9xZlRZ
            L0M1a0ZKVkJJY0hOT3VSTDhFeERWK3MKLS0tIGU5aU00S3VQdDhmSno3bFVNQ2Zu
            M1dZQVVZaGFUYjRVWXNjY05ONUpsV00KmvL3HlMSddeDKrEJ8GZsCXdKsybdUJVd
            SoPaoT81eXcTfjSp+HD9i3YRGm5D4g2WUXj1eZCdgWqfB/uVUEi+rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:18:14Z"
    mac: ENC[AES256_GCM,data:TycUAUKEXfF77BXn5ZU0Czc3fcjBYElEwhMCRTFmGQ8LUoVyypdOXUaA9Kda/jgJT2LvwfwkqceIeUh4bUx/QupBME+x1YapdC37Ei+wZ4sskCT/fpj4bFW1FzioG3vUpk+pjkDdKQcmpLcMYA/xoEq8vd9DyDSnbPqlYgWnYUg=,iv:JnxL0MQfKKoqT1E0TavfITaSkk7Nn7Jf6dhgq3pcMSs=,tag:upP2jKYZNTSGb46expWVJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
