apiVersion: v1
kind: Secret
metadata:
    name: qui
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:Dd/s7fyy9AY5rUiSyO2w/sWOySziE7eJtWbG0sHg693BrTuVkhHPMgOCcghz+IDOPsFbAfvKN12rRsf3MI/geuHQme/XR1/Ne0+5ma9mCqQ4rlVYYPRPA8vnNNrT1ZbdeTDMjaPIYUEVTtmRXfAD3jxmHHFxKUd4lbQooPQ1RNN0y94cOkBc0ER162mHHuTylWjlm24IQpC0qdCDt/ZBGXkK98hqn/7+8gF28KRlG7urcZg+lsImHvE61OagXYsWqd2hzfaPoBbvKS+5lPdCk4PyX9pssDwvjpufR0Yf4RAPe4gIOr7+VY6lc0IUXv64gaQ0G0zYN1OYcbDtYA==,iv:GZ6PXIE72jIZtsf6hZozkn5MnOchIA+4TCEkClEhUSQ=,tag:iJCy+wxep6Fp/gpkrC3mdA==,type:str]
sops:
    age:
        - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreDl2NEo5allvOHpYOHpV
            WHBjMWhkOWtxMFcxdDE1bTA1MStPekQraGhNClR3dCtHMXg5NDE3MjR3TXZ2Z1BW
            d0xOUG5GM2EvMm5kTGdvNVBNbGtpYmcKLS0tIGZjYUJzNW10cW9BQStheDQ2SXNS
            K2pFY2FqL0hqSWo5TjJnY29jWGt5UUEKIonkEqe27cfLRP6Rw1SBVmzihY7uUihQ
            gGM4JzvjelUFhIgnK1jybj8lJBCxWdJpJh1xEopSUWxfCS+W+nBiRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T23:13:11Z"
    mac: ENC[AES256_GCM,data:U17HNMXSQqEsSe4draA9SsRwXYiai0o4Bg92vR9coV5O6c9QdR9jN7KRUIBgoGNPSbFpXQPsRqiLARe9ncZfrR2pPdw6jSk8r9kQ67S3nKq0K1Pz08XtUt+ImUgo7+LLrfh/PeIq3WsKqqNMcjgIWr0xsrdirnlCo8NuIN2kwDk=,iv:xK7nUkVgTkKq9K5fzrzDoCRbbcM2rcsEH7s5QWgXZoo=,tag:vdqL0KnrbS1mM7LliN1lVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
