---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backrest-userdata
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/backups
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
