---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-33aa5dcb-8a2b-4575-86a5-61a0613ddd72
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-movies
spec:
  volumeName: jellyfin-movies
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-tv
spec:
  volumeName: jellyfin-tv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-channels
spec:
  volumeName: jellyfin-channels
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
