---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        # sysctls:
        #   - name: net.ipv4.conf.all.src_valid_mark
        #     value: "1"
        #   - name: net.ipv6.conf.all.disable_ipv6
        #     value: "1"
      enableServiceLinks: true
      initContainers:
      - name: init-config
        image: busybox:latest
        command:
          - sh
          - -c
          - |
            set -eu
            mkdir -p /config/wireguard
            cp /wireguard/wg0.conf /config/wireguard/wg0.conf
            chmod 600 /config/wireguard/wg0.conf
            chown 1000:1000 /config/wireguard/wg0.conf || true
        volumeMounts:
          - name: qbittorrent-data
            mountPath: /config
          - name: qbittorrent-wg0
            mountPath: /wireguard
            readOnly: true
      containers:
      - name: qbittorrent
        image: ghcr.io/hotio/qbittorrent:latest
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TZ
          value: "Europe/London"
        - name: VPN_ENABLED
          value: "true"
        - name: VPN_LAN_NETWORK
          value: "0.0.0.0/0"
        - name: VPN_LAN_LEAK_ENABLED
          value: "true"
        - name: VPN_CONF
          value: "wg0"
        - name: PRIVOXY_ENABLED
          value: "false"
        volumeMounts:
        - name: qbittorrent-data
          mountPath: /config
        - name: qbittorrent-downloads
          mountPath: /downloads
      volumes:
      - name: qbittorrent-data
        persistentVolumeClaim:
          claimName: qbittorrent-data
      - name: qbittorrent-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: qbittorrent-wg0
        secret:
          secretName: qbittorrent
          items:
            - key: wg0.conf
              path: wg0.conf
