---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      securityContext:
        # sysctls:
        #   - name: net.ipv4.conf.all.src_valid_mark
        #     value: "1"
        #   - name: net.ipv6.conf.all.disable_ipv6
        #     value: "1"
      enableServiceLinks: true
      initContainers:
      - name: init-config
        image: alpine:latest
        command:
          - sh
          - -c
          - |
            mkdir -p /config/wireguard
            cp /wireguard/wg0.conf /config/wireguard/wg0.conf
        volumeMounts:
          - name: qbittorrent-data
            mountPath: /config
          - name: qbittorrent-wg0
            mountPath: /wireguard
            readOnly: true
      containers:
      - name: qbittorrent
        image: ghcr.io/hotio/qbittorrent:latest
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN"]
        command: ["/bin/sh","-c"]
        # args:
        #   - |
        #     ip link del wg0 2>/dev/null || true
        #     exec /init
        args:
          - |
            ip link del wg0 2>/dev/null || true
            CONF="/config/wireguard/wg0.conf"
            if [ -f "$CONF" ]; then
              ENDPOINT_IP="$(awk -F' *= *' '/^Endpoint *=/ {print $2}' "$CONF" | cut -d: -f1 || true)"
              if [ -n "${ENDPOINT_IP:-}" ]; then
                ip -4 route del "${ENDPOINT_IP}/32" 2>/dev/null || true
              fi
            fi
            ip -4 route del 192.168.0.0/16 2>/dev/null || true
            ip -4 route del 10.42.0.0/16   2>/dev/null || true
            exec /init
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: TZ
          value: "Europe/London"
        - name: VPN_ENABLED
          value: "true"
        - name: VPN_LAN_NETWORK
          value: "192.168.0.0/16,10.42.0.0/16"
        - name: VPN_LAN_LEAK_ENABLED
          value: "true"
        - name: VPN_CONF
          value: "wg0"
        - name: PRIVOXY_ENABLED
          value: "false"
        volumeMounts:
        - name: qbittorrent-data
          mountPath: /config
        - name: qbittorrent-downloads
          mountPath: /downloads
      volumes:
      - name: qbittorrent-data
        persistentVolumeClaim:
          claimName: qbittorrent-data
      - name: qbittorrent-downloads
        persistentVolumeClaim:
          claimName: qbittorrent-downloads
      - name: qbittorrent-wg0
        secret:
          secretName: qbittorrent
          items:
            - key: wg0.conf
              path: wg0.conf
