---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-6d0b3e8d-d2d4-4800-a7ab-687757cd9bb5
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-downloads
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: qbittorrent-downloads
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
