apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:12OJ0lU4jFb9yJloRyLWu4+oAadBhNoNtWuH0f/XM4BitdXsc2dElxcTxqjLlx30CvrrwywhYtfN/T6tjKuN43MgqgiRQd9/pDfmouNoG8t9MbQOAybGNjkgAfS8Bb+GhpCfEtDIE7yXzj6jOVYVy39nSToODUn4RaPfIowd3SyBsckbtNsXVzSzVy47EoSY8+u0zldSZonhebpdLg88krdxgH0H8Lk8T8MxGs4rqpfJpHOFMu8BoMZRGQAFQWSXVH55ht6TQmeDGErhxy/paJDCPd+ePTr/TGsJGL3jddgOWN5bcXlxoCsM7izZPSXURfSz2kmkwBfvJXhSM8zI3m5bZJOpxcQ41br+q5bMZXE2OJMcOtO0oQg4DhRaY05JIIJa,iv:yLmGk/uGDgheDLXM4utTOJq29m5ZS4NJPCmA2TQtx9o=,tag:1wveHw8mieDmDsjFkswtbg==,type:str]
sops:
    age:
        - recipient: age166emlwc4zzzdzfjeurrxtk05wnz6dqxdnujr2u6h63c800dutsxstyl7n9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeG16bjFGck93NHBuL1Vv
            bER6bVFGaG02ZURGNHgxdFIzWDh6ZnRJWEcwCkRoOWIxNG1pK0g1blIzUURTTVZr
            eC91c1NKeXA3L0NsUE1wekIwaDFoUzgKLS0tIFpadGUxQ2RWM2ZINUd2azNpZmUv
            dUVKUldPaHRXRkZ6b0JlNlJkWnR5bTgKJOBdZ9vEX9i/GVnY3fj9BrJth524r9xI
            iywjEvJfGb/IyT2+z6aYp7aKiFwqB2dmcgBq1Gd32lTVGw5i7YjqxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-26T15:46:18Z"
    mac: ENC[AES256_GCM,data:Dgq0c/3E0Debyk6k3em8sEQa4DVh+k4uKSxjnjD12uDiSASUos+2SaA87k595Z1l71oD7WQTNoWXwvU85/ZY3F295vvX2PNsyv0/i35XPgxNJ7/p6u/lfkEPq1/3edx8EQ1KP/ySrc7rv/bL+mp1JEXOHCyq0+tkGwdeK1JKjio=,iv:WfQC91HBoJP9ers4r4CP3nvAaX7gvF6d/RvMpzu3zOw=,tag:IqItOQo0+TELjJxOd8uikw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
