apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent
type: Opaque
stringData:
    wg0.conf: |-
        [Interface]
        # Device: Lawful Cobra
        PrivateKey = CHL7gdhUd00zU7Djy0HzbR0jyZJuDzXU704ZZTnbfmM=
        Address = 10.64.56.199/32
        DNS = 10.64.0.1

        [Peer]
        PublicKey = /iivwlyqWqxQ0BVWmJRhcXIFdJeo0WbHQ/hZwuXaN3g=
        AllowedIPs = 0.0.0.0/0
        Endpoint = 193.32.127.66:51820
