---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: pvc-56ccd364-c025-427b-99f5-ff10e91f44b9
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-movies
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: radarr-movies
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-downloads
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: radarr-downloads
  storageClassName: ""
  resources:
    requests:
      storage: 8Ti
