---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-tv
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/tv
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-downloads
spec:
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  nfs:
    path: /mnt/tank/media/downloads
    server: scale.lan
  persistentVolumeReclaimPolicy: Retain
